/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VerifyEmailImport } from './routes/verify-email'
import { Route as SsoCallbackImport } from './routes/sso-callback'
import { Route as SsoCallbaccImport } from './routes/sso-callbacc'
import { Route as LoginImport } from './routes/login'
import { Route as PrivateImport } from './routes/_private'
import { Route as IndexImport } from './routes/index'
import { Route as StoreStorenameImport } from './routes/store.$store_name'
import { Route as PrivateTagsIndexImport } from './routes/_private.tags/index'
import { Route as PrivateStoresIndexImport } from './routes/_private.stores/index'
import { Route as PrivateProductsIndexImport } from './routes/_private.products/index'
import { Route as PrivateOrdersIndexImport } from './routes/_private.orders/index'
import { Route as PrivateDashboardIndexImport } from './routes/_private.dashboard/index'
import { Route as PrivateCategoriesIndexImport } from './routes/_private.categories/index'
import { Route as PrivateAnalyticsIndexImport } from './routes/_private.analytics/index'
import { Route as PrivateStoresCreateImport } from './routes/_private.stores/create'
import { Route as PrivateProductsCreateImport } from './routes/_private.products/create'
import { Route as PrivateStoresEditIdImport } from './routes/_private.stores/edit.$id'
import { Route as PrivateProductsEditIdImport } from './routes/_private.products/edit.$id'

// Create/Update Routes

const VerifyEmailRoute = VerifyEmailImport.update({
  path: '/verify-email',
  getParentRoute: () => rootRoute,
} as any)

const SsoCallbackRoute = SsoCallbackImport.update({
  path: '/sso-callback',
  getParentRoute: () => rootRoute,
} as any)

const SsoCallbaccRoute = SsoCallbaccImport.update({
  path: '/sso-callbacc',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StoreStorenameRoute = StoreStorenameImport.update({
  path: '/store/$store_name',
  getParentRoute: () => rootRoute,
} as any)

const PrivateTagsIndexRoute = PrivateTagsIndexImport.update({
  path: '/tags/',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateStoresIndexRoute = PrivateStoresIndexImport.update({
  path: '/stores/',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateProductsIndexRoute = PrivateProductsIndexImport.update({
  path: '/products/',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateOrdersIndexRoute = PrivateOrdersIndexImport.update({
  path: '/orders/',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateDashboardIndexRoute = PrivateDashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateCategoriesIndexRoute = PrivateCategoriesIndexImport.update({
  path: '/categories/',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateAnalyticsIndexRoute = PrivateAnalyticsIndexImport.update({
  path: '/analytics/',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateStoresCreateRoute = PrivateStoresCreateImport.update({
  path: '/stores/create',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateProductsCreateRoute = PrivateProductsCreateImport.update({
  path: '/products/create',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateStoresEditIdRoute = PrivateStoresEditIdImport.update({
  path: '/stores/edit/$id',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateProductsEditIdRoute = PrivateProductsEditIdImport.update({
  path: '/products/edit/$id',
  getParentRoute: () => PrivateRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/sso-callbacc': {
      id: '/sso-callbacc'
      path: '/sso-callbacc'
      fullPath: '/sso-callbacc'
      preLoaderRoute: typeof SsoCallbaccImport
      parentRoute: typeof rootRoute
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackImport
      parentRoute: typeof rootRoute
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailImport
      parentRoute: typeof rootRoute
    }
    '/store/$store_name': {
      id: '/store/$store_name'
      path: '/store/$store_name'
      fullPath: '/store/$store_name'
      preLoaderRoute: typeof StoreStorenameImport
      parentRoute: typeof rootRoute
    }
    '/_private/products/create': {
      id: '/_private/products/create'
      path: '/products/create'
      fullPath: '/products/create'
      preLoaderRoute: typeof PrivateProductsCreateImport
      parentRoute: typeof PrivateImport
    }
    '/_private/stores/create': {
      id: '/_private/stores/create'
      path: '/stores/create'
      fullPath: '/stores/create'
      preLoaderRoute: typeof PrivateStoresCreateImport
      parentRoute: typeof PrivateImport
    }
    '/_private/analytics/': {
      id: '/_private/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof PrivateAnalyticsIndexImport
      parentRoute: typeof PrivateImport
    }
    '/_private/categories/': {
      id: '/_private/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof PrivateCategoriesIndexImport
      parentRoute: typeof PrivateImport
    }
    '/_private/dashboard/': {
      id: '/_private/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardIndexImport
      parentRoute: typeof PrivateImport
    }
    '/_private/orders/': {
      id: '/_private/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof PrivateOrdersIndexImport
      parentRoute: typeof PrivateImport
    }
    '/_private/products/': {
      id: '/_private/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof PrivateProductsIndexImport
      parentRoute: typeof PrivateImport
    }
    '/_private/stores/': {
      id: '/_private/stores/'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof PrivateStoresIndexImport
      parentRoute: typeof PrivateImport
    }
    '/_private/tags/': {
      id: '/_private/tags/'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof PrivateTagsIndexImport
      parentRoute: typeof PrivateImport
    }
    '/_private/products/edit/$id': {
      id: '/_private/products/edit/$id'
      path: '/products/edit/$id'
      fullPath: '/products/edit/$id'
      preLoaderRoute: typeof PrivateProductsEditIdImport
      parentRoute: typeof PrivateImport
    }
    '/_private/stores/edit/$id': {
      id: '/_private/stores/edit/$id'
      path: '/stores/edit/$id'
      fullPath: '/stores/edit/$id'
      preLoaderRoute: typeof PrivateStoresEditIdImport
      parentRoute: typeof PrivateImport
    }
  }
}

// Create and export the route tree

interface PrivateRouteChildren {
  PrivateProductsCreateRoute: typeof PrivateProductsCreateRoute
  PrivateStoresCreateRoute: typeof PrivateStoresCreateRoute
  PrivateAnalyticsIndexRoute: typeof PrivateAnalyticsIndexRoute
  PrivateCategoriesIndexRoute: typeof PrivateCategoriesIndexRoute
  PrivateDashboardIndexRoute: typeof PrivateDashboardIndexRoute
  PrivateOrdersIndexRoute: typeof PrivateOrdersIndexRoute
  PrivateProductsIndexRoute: typeof PrivateProductsIndexRoute
  PrivateStoresIndexRoute: typeof PrivateStoresIndexRoute
  PrivateTagsIndexRoute: typeof PrivateTagsIndexRoute
  PrivateProductsEditIdRoute: typeof PrivateProductsEditIdRoute
  PrivateStoresEditIdRoute: typeof PrivateStoresEditIdRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateProductsCreateRoute: PrivateProductsCreateRoute,
  PrivateStoresCreateRoute: PrivateStoresCreateRoute,
  PrivateAnalyticsIndexRoute: PrivateAnalyticsIndexRoute,
  PrivateCategoriesIndexRoute: PrivateCategoriesIndexRoute,
  PrivateDashboardIndexRoute: PrivateDashboardIndexRoute,
  PrivateOrdersIndexRoute: PrivateOrdersIndexRoute,
  PrivateProductsIndexRoute: PrivateProductsIndexRoute,
  PrivateStoresIndexRoute: PrivateStoresIndexRoute,
  PrivateTagsIndexRoute: PrivateTagsIndexRoute,
  PrivateProductsEditIdRoute: PrivateProductsEditIdRoute,
  PrivateStoresEditIdRoute: PrivateStoresEditIdRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof PrivateRouteWithChildren
  '/login': typeof LoginRoute
  '/sso-callbacc': typeof SsoCallbaccRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/verify-email': typeof VerifyEmailRoute
  '/store/$store_name': typeof StoreStorenameRoute
  '/products/create': typeof PrivateProductsCreateRoute
  '/stores/create': typeof PrivateStoresCreateRoute
  '/analytics': typeof PrivateAnalyticsIndexRoute
  '/categories': typeof PrivateCategoriesIndexRoute
  '/dashboard': typeof PrivateDashboardIndexRoute
  '/orders': typeof PrivateOrdersIndexRoute
  '/products': typeof PrivateProductsIndexRoute
  '/stores': typeof PrivateStoresIndexRoute
  '/tags': typeof PrivateTagsIndexRoute
  '/products/edit/$id': typeof PrivateProductsEditIdRoute
  '/stores/edit/$id': typeof PrivateStoresEditIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof PrivateRouteWithChildren
  '/login': typeof LoginRoute
  '/sso-callbacc': typeof SsoCallbaccRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/verify-email': typeof VerifyEmailRoute
  '/store/$store_name': typeof StoreStorenameRoute
  '/products/create': typeof PrivateProductsCreateRoute
  '/stores/create': typeof PrivateStoresCreateRoute
  '/analytics': typeof PrivateAnalyticsIndexRoute
  '/categories': typeof PrivateCategoriesIndexRoute
  '/dashboard': typeof PrivateDashboardIndexRoute
  '/orders': typeof PrivateOrdersIndexRoute
  '/products': typeof PrivateProductsIndexRoute
  '/stores': typeof PrivateStoresIndexRoute
  '/tags': typeof PrivateTagsIndexRoute
  '/products/edit/$id': typeof PrivateProductsEditIdRoute
  '/stores/edit/$id': typeof PrivateStoresEditIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteWithChildren
  '/login': typeof LoginRoute
  '/sso-callbacc': typeof SsoCallbaccRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/verify-email': typeof VerifyEmailRoute
  '/store/$store_name': typeof StoreStorenameRoute
  '/_private/products/create': typeof PrivateProductsCreateRoute
  '/_private/stores/create': typeof PrivateStoresCreateRoute
  '/_private/analytics/': typeof PrivateAnalyticsIndexRoute
  '/_private/categories/': typeof PrivateCategoriesIndexRoute
  '/_private/dashboard/': typeof PrivateDashboardIndexRoute
  '/_private/orders/': typeof PrivateOrdersIndexRoute
  '/_private/products/': typeof PrivateProductsIndexRoute
  '/_private/stores/': typeof PrivateStoresIndexRoute
  '/_private/tags/': typeof PrivateTagsIndexRoute
  '/_private/products/edit/$id': typeof PrivateProductsEditIdRoute
  '/_private/stores/edit/$id': typeof PrivateStoresEditIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/sso-callbacc'
    | '/sso-callback'
    | '/verify-email'
    | '/store/$store_name'
    | '/products/create'
    | '/stores/create'
    | '/analytics'
    | '/categories'
    | '/dashboard'
    | '/orders'
    | '/products'
    | '/stores'
    | '/tags'
    | '/products/edit/$id'
    | '/stores/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/sso-callbacc'
    | '/sso-callback'
    | '/verify-email'
    | '/store/$store_name'
    | '/products/create'
    | '/stores/create'
    | '/analytics'
    | '/categories'
    | '/dashboard'
    | '/orders'
    | '/products'
    | '/stores'
    | '/tags'
    | '/products/edit/$id'
    | '/stores/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/login'
    | '/sso-callbacc'
    | '/sso-callback'
    | '/verify-email'
    | '/store/$store_name'
    | '/_private/products/create'
    | '/_private/stores/create'
    | '/_private/analytics/'
    | '/_private/categories/'
    | '/_private/dashboard/'
    | '/_private/orders/'
    | '/_private/products/'
    | '/_private/stores/'
    | '/_private/tags/'
    | '/_private/products/edit/$id'
    | '/_private/stores/edit/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  LoginRoute: typeof LoginRoute
  SsoCallbaccRoute: typeof SsoCallbaccRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  StoreStorenameRoute: typeof StoreStorenameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  LoginRoute: LoginRoute,
  SsoCallbaccRoute: SsoCallbaccRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  StoreStorenameRoute: StoreStorenameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_private",
        "/login",
        "/sso-callbacc",
        "/sso-callback",
        "/verify-email",
        "/store/$store_name"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_private": {
      "filePath": "_private.tsx",
      "children": [
        "/_private/products/create",
        "/_private/stores/create",
        "/_private/analytics/",
        "/_private/categories/",
        "/_private/dashboard/",
        "/_private/orders/",
        "/_private/products/",
        "/_private/stores/",
        "/_private/tags/",
        "/_private/products/edit/$id",
        "/_private/stores/edit/$id"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/sso-callbacc": {
      "filePath": "sso-callbacc.tsx"
    },
    "/sso-callback": {
      "filePath": "sso-callback.tsx"
    },
    "/verify-email": {
      "filePath": "verify-email.tsx"
    },
    "/store/$store_name": {
      "filePath": "store.$store_name.tsx"
    },
    "/_private/products/create": {
      "filePath": "_private.products/create.tsx",
      "parent": "/_private"
    },
    "/_private/stores/create": {
      "filePath": "_private.stores/create.tsx",
      "parent": "/_private"
    },
    "/_private/analytics/": {
      "filePath": "_private.analytics/index.tsx",
      "parent": "/_private"
    },
    "/_private/categories/": {
      "filePath": "_private.categories/index.tsx",
      "parent": "/_private"
    },
    "/_private/dashboard/": {
      "filePath": "_private.dashboard/index.tsx",
      "parent": "/_private"
    },
    "/_private/orders/": {
      "filePath": "_private.orders/index.tsx",
      "parent": "/_private"
    },
    "/_private/products/": {
      "filePath": "_private.products/index.tsx",
      "parent": "/_private"
    },
    "/_private/stores/": {
      "filePath": "_private.stores/index.tsx",
      "parent": "/_private"
    },
    "/_private/tags/": {
      "filePath": "_private.tags/index.tsx",
      "parent": "/_private"
    },
    "/_private/products/edit/$id": {
      "filePath": "_private.products/edit.$id.tsx",
      "parent": "/_private"
    },
    "/_private/stores/edit/$id": {
      "filePath": "_private.stores/edit.$id.tsx",
      "parent": "/_private"
    }
  }
}
ROUTE_MANIFEST_END */
